Initial commit

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -5,95 +5,64 @@ on:
   workflow_call:
 
 jobs:
-  checkov:
-    name: "Static code analysis"
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Checkout"
-        uses: actions/checkout@v2
+  # checkov:
+  #   name: "Static code analysis"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: "Checkout"
+  #       uses: actions/checkout@v2
 
-      - name: "Run Checkov by bridgecrew.io"
-        id: checkov
-        uses: bridgecrewio/checkov-action@master
-        with:
-          framework: terraform
-          directory: terraform
-          skip_check: CKV_GIT_1
+  #     - name: "Run Checkov by bridgecrew.io"
+  #       id: checkov
+  #       uses: bridgecrewio/checkov-action@master
+  #       with:
+  #         framework: terraform
+  #         directory: terraform
+  #         skip_check: CKV_GIT_1
 
   plan:
     name: "Plan"
     runs-on: ubuntu-latest
-    needs:
-      - checkov
+    # needs:
+    #   - checkov
     steps:
-      - name: "Checkout"
-        uses: actions/checkout@v2
+      - name: "Run Checkout by Actions"
+        uses: letsrockthefuture/reusable-workflows/workflows/checkout@main
 
-      - name: "Set up credentials"
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.1.0
-          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
+      - name: "Set up Terraform credentials"
+        uses: letsrockthefuture/reusable-workflows/workflows/terraform@main
+        # with:
+          # terraform_version: 1.1.0
+          # cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
 
       - name: "Plan"
-        id: terraform_plan
+        uses: letsrockthefuture/reusable-workflows/workflows/terraform/plan@main
+        # id: terraform_plan
         # if: github.event_name == 'pull_request'
-        continue-on-error: true
-        run: |
-          make init
-          make terraform/plan
+        # continue-on-error: true
+        # run: |
+        #   make init
+        #   make terraform/plan
 
-      - name: "Plan status"
-        if: steps.terraform_plan.outcome == 'failure'
-        run: |
-          exit 1
+      # - name: "Plan status"
+      #   if: steps.terraform_plan.outcome == 'failure'
+      #   run: |
+      #     exit 1
 
-      - name: "Update pull request"
-        uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          TERRAFORM_PLAN: "terraform\n${{ steps.terraform_plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform plan 📖: \`${{ steps.terraform_plan.outcome }}\`
+  # apply:
+  #   name: "Apply"
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - plan
+  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+  #   environment:
+  #     name: production
+  #   steps:
+  #     - name: "Run Checkout by Actions"
+  #       uses: letsrockthefuture/reusable-workflows/workflows/checkout@main
 
-            <details><summary>Show plan</summary>
+  #     - name: "Set up Terraform credentials"
+  #       uses: letsrockthefuture/reusable-workflows/workflows/terraform@main
 
-            \`\`\`\n
-            ${process.env.TERRAFORM_PLAN}
-            \`\`\`
-
-            </details>
-
-            *Actor: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.working-directory }}\`, Workflow: \`${{ github.workflow }}\`*`;
-
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-  apply:
-    name: "Apply"
-    runs-on: ubuntu-latest
-    needs:
-      - plan
-    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-    environment:
-      name: production
-    steps:
-      - name: "Checkout"
-        uses: actions/checkout@v2
-
-      - name: "Set up credentials"
-        uses: hashicorp/setup-terraform@v1
-        with:
-          terraform_version: 1.1.0
-          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
-
-      - name: "Apply"
-        run: |
-          make init
-          make terraform/apply
+  #     - name: "Apply"
+  #       uses: letsrockthefuture/reusable-workflows/workflows/terraform/apply@main
